version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # デフォルトのポートを指定
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./next.config.js:/app/next.config.js
    environment:
      - NODE_ENV=development
